### ISSUE TITLE
pseudocode

### ISSUE THREAD

**Issue by lucidrains** [lucidrains/gated-state-spaces-pytorch#1]
in the pseudocode of the paper, why isn't it `irfft(u_f * K_f.conj())` ?

![Screenshot from 2022-07-02 17-31-54](https://user-images.githubusercontent.com/108653/177020024-f3cc7c44-8488-4ef4-8bc2-e0fcef349888.png)

**Comment by lucidrains** [comment]
GSS seems to be training fine, so maybe this was intended, but i thought in the pseudocode above, `y` should come out equivalent to `F.conv1d(u, K)` but it doesn't seem to be so

**Comment by lucidrains** [comment]
nevermind, i think the pseudocode is correct, because once i change it it starts to perform horribly

the conjugate must have been taken care of during the simplified dss kernel creation

**Comment by albertfgu** [comment]
There shouldn't be a conjugate in the FFT convolution.

```python
>>> import numpy as np
>>> a = 1+np.arange(4)
>>> a_f = np.fft.rfft(a, 8)
>>> np.fft.irfft(a_f*a_f, 8)[:4]
array([ 1.,  4., 10., 20.])
```
This correctly gives the convolution of `1 2 3 4` by itself, which is given by reversing one vector and convolving.
```
      1 2 3 4
      *              = 1
4 3 2 1
```
 
```
    1 2 3 4
     *               = 4
4 3 2 1
```

```
  1 2 3 4
    *                = 10
4 3 2 1
```

```
1 2 3 4
   *                 = 20
4 3 2 1
```

**Comment by lucidrains** [comment]
ohh got it! i think the conjugate just reverses the kernel along the sequence dimension, which isn't needed here

**Comment by albertfgu** [comment]
Yeah that's right, the kernel actually wants to be reversed. That's because the kernel represents successive powers of A, and you want larger powers going backwards in time.
