### ISSUE TITLE
Very small discrepency in kernel construction

### ISSUE THREAD

**Issue by albertfgu** [lucidrains/gated-state-spaces-pytorch#2]
Read the code and it all looks good. There's a very tiny difference in the parameterization of $\Lambda$: you use
```python
Lambda = -self.Lambda_real.exp() + 1j * self.Lambda_imag.exp()
```
but DSS/S4D don't put an exp on the imaginary part
```python
Lambda = -self.Lambda_real_log.exp() + 1j * self.Lambda_imag
```
The exp is to ensure the real part is negative which can be important for unbounded settings (e.g. generation). I doubt the difference between these parameterizations will make any difference though.

I can also share my own experiments with this model. I ran two datasets (sequential CIFAR and Speech Commands) and found quite different behavior than what the paper found for LM.
1. I found that the gating actually hurts performance, controlling for parameters/speed (on **GPU**). From talking to the authors my understanding is that the gating is mainly a computational trick - it's used to move more parameters into FFN and less into the SSM since the FFT is so slow on TPU
2. The random initialization works fine on CIFAR (just 1-2% worse) - but it's really bad on SC. I think it might vary a lot depending on the characteristics of the data, so I'd believe that it works on LM but I'd be shocked if it works on PathX. Curious to see how your experiments turn out.

**Comment by lucidrains** [comment]
@albertfgu hey Albert and hope you have been well! thank you for the correction; I've added it as a setting that can be toggled to how you had it in S4 vs the pseudocode in this paper
<img width="438" alt="Screen Shot 2022-07-14 at 5 24 37 PM" src="https://user-images.githubusercontent.com/108653/179122621-490be08d-fb02-4443-b3ff-6a8cc6218f7e.png">

will come back to this soon to spend a few days running experiments. mainly i want to see if adding state spaces (or dsconv / mhesa) can help fix the [length generalization problem ](https://arxiv.org/abs/2207.04901) in transformers

have you read [Goodbye Wavenet](https://arxiv.org/abs/2206.08297) by any chance?

**Comment by albertfgu** [comment]
To be clear, I don't think this will make any difference at all - just pointing out a very slight difference :P. Also I don't know if anyone has tried adding a LayerNorm in the beginning like you do, but it probably doesn't hurt either.

I've talked about the Goodbye Wavenet paper with a couple of audio experts and the consensus for now is that it's difficult to assess without code and samples. Also their eval-time NLL calculation is slightly different than the way we do it which might cause some discrepancies in results.

**Comment by lucidrains** [comment]
@albertfgu ok cool! yea i'll let you know how the pathx experiments go once i get around to them!

**Comment by albertfgu** [comment]
Ended up checking the GSS paper again for reference to something and realized the way you did it is the way they described it in the text and pseudocode. The alternative I mentioned was described in S4/DSS and I mistakenly thought that's what they did for GSS as well. Either way, shouldn't make a difference.
